/**
 * ═══════════════════════════════════════════════════════════════════════════════
 *  QRDX Wallet — Post-Quantum Signatures (ML-DSA-65 / FIPS 204)
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 *  Real ML-DSA-65 — the NIST standard formerly known as Dilithium3 — implemented
 *  with `@noble/post-quantum`, a pure-TypeScript FIPS 204 implementation that
 *  runs unchanged in the extension, the web app, and React Native. There is no
 *  native module and no WASM to load.
 *
 *  This replaces a placeholder that derived "public keys" by repeating a
 *  SHA-256 digest to 1952 bytes and "signed" by SHA-256 expansion. Those values
 *  had the right *shape* but no cryptographic meaning: the node verifies with
 *  liboqs and would have rejected every signature, and the PQ addresses shown
 *  in the UI belonged to key pairs that could never sign for them.
 *
 *  ── Interoperability with the node ──────────────────────────────────────────
 *
 *  `ref/qrdx-chain/qrdx/crypto/pq/dilithium.py` states it requires liboqs and
 *  has no fallback, so wallet and chain must agree byte-for-byte. They do:
 *  signatures produced here verify under liboqs ML-DSA-65 and vice versa, which
 *  `tests/unit/pq.test.ts` and `tests/integration/pq-liboqs.test.ts` check
 *  against vectors generated by liboqs itself rather than by this code.
 *
 *  Sizes match the node's constants exactly: 4032-byte secret key, 1952-byte
 *  public key, 3309-byte signature.
 *
 *  ── Why keys are seeded ─────────────────────────────────────────────────────
 *
 *  The node generates PQ keys with liboqs' randomised `generate_keypair()` and
 *  stores the 4032-byte secret. A wallet cannot do that and still honour its
 *  central promise — that the recovery phrase restores the account. FIPS 204
 *  key generation is deterministic in its 32-byte seed, so the wallet derives
 *  that seed from the BIP-39 mnemonic and keeps only the seed. The resulting
 *  key pair is an ordinary ML-DSA-65 key pair; the node cannot tell how it was
 *  produced, and it is fully recoverable from the phrase.
 */

import { ml_dsa65 } from '@noble/post-quantum/ml-dsa.js'
import { keccak256 } from 'ethereum-cryptography/keccak.js'
import { sha256 } from 'ethereum-cryptography/sha256.js'
import { getRandomBytesSync } from 'ethereum-cryptography/random.js'
import { mnemonicToSeedSync } from 'ethereum-cryptography/bip39/index.js'
import { hmac } from '@noble/hashes/hmac.js'
import { sha512 } from '@noble/hashes/sha2.js'
import { bytesToHex, hexToBytes, toPqChecksumAddress } from './crypto'

// ─── Parameters ─────────────────────────────────────────────────────────────

/** ML-DSA-65 byte lengths. These mirror `qrdx/crypto/pq/dilithium.py`. */
export const PQ_SIZES = {
  /** Secret key as serialised by FIPS 204. */
  secretKey: 4032,
  publicKey: 1952,
  signature: 3309,
  /** Key-generation seed (ξ). */
  seed: 32,
  /** Address body: first 32 bytes of keccak256(publicKey). */
  addressBytes: 32,
} as const

/**
 * Domain separation tag for PQ seed derivation.
 *
 * Versioned because changing the derivation changes every PQ address: a future
 * scheme must use a new tag rather than silently relocating existing accounts.
 */
const PQ_SEED_DOMAIN = 'QRDX-PQ-seed/ML-DSA-65/v1'

// ─── Types ──────────────────────────────────────────────────────────────────

export interface PqKeyPair {
  /**
   * 32-byte hex seed. This is what the wallet persists — the secret key is
   * regenerated from it on demand, so there is no 4032-byte blob at rest.
   *
   * Named `privateKey` for continuity with the stored wallet format, where this
   * field has always held the seed.
   */
  privateKey: string
  /** Full 4032-byte secret key, hex. Derived; never persisted. */
  secretKey: string
  /** 1952-byte public key, hex. Must be stored — it cannot be recovered from an address. */
  publicKey: string
  /** `0xPQ`-prefixed checksummed address. */
  address: string
  /** First 8 bytes of SHA-256(publicKey), hex — a short human-comparable id. */
  fingerprint: string
}

/** Raised when PQ key material is malformed or inconsistent. */
export class PqKeyError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'PqKeyError'
  }
}

// ─── Derivation ─────────────────────────────────────────────────────────────

/**
 * Reduce arbitrary input to a 32-byte ML-DSA seed.
 *
 * Accepts any length so existing callers holding a 64-byte seed keep working,
 * and so the same helper serves mnemonic and raw-entropy paths. HMAC-SHA-512
 * under a fixed domain tag gives a uniform 32 bytes and keeps this derivation
 * from colliding with any other use of the same input.
 */
function deriveSeed32(input: Uint8Array, label: string): Uint8Array {
  return hmac(sha512, new TextEncoder().encode(label), input).slice(0, 32)
}

/**
 * Derive the PQ seed for an account from a BIP-39 mnemonic.
 *
 * Deliberately derived from the mnemonic seed rather than from the account's
 * secp256k1 private key. Deriving PQ material from an ECDSA key would make the
 * post-quantum key only as strong as the classical one: an adversary able to
 * break secp256k1 — the exact adversary ML-DSA exists to defend against —
 * could recompute the PQ key and forge its signatures.
 *
 * @param index HD account index, so each account gets a distinct PQ key.
 */
export function derivePqSeedFromMnemonic(mnemonic: string, index = 0): Uint8Array {
  const bip39Seed = mnemonicToSeedSync(mnemonic.trim().toLowerCase())
  return deriveSeed32(bip39Seed, `${PQ_SEED_DOMAIN}/${index}`)
}

// ─── Key pairs ──────────────────────────────────────────────────────────────

/** Build the public parts of a key pair from a raw ML-DSA public key. */
function describePublicKey(publicKey: Uint8Array): {
  address: string
  fingerprint: string
} {
  // Matches PQPublicKey.to_address(): first 32 bytes of keccak256(pubkey).
  const address = toPqChecksumAddress(bytesToHex(keccak256(publicKey).slice(0, 32)))
  // Matches PQPublicKey.fingerprint(): first 8 bytes of SHA-256(pubkey).
  const fingerprint = bytesToHex(sha256(publicKey).slice(0, 8))
  return { address, fingerprint }
}

/**
 * Generate a key pair from a seed.
 *
 * Any seed length is accepted and folded to the 32 bytes FIPS 204 requires, so
 * a caller with 64 bytes of entropy does not have to decide how to truncate it.
 */
export async function pqKeyPairFromSeed(seed: Uint8Array): Promise<PqKeyPair> {
  if (seed.length === 0) {
    throw new PqKeyError('PQ seed is empty')
  }

  const seed32 =
    seed.length === PQ_SIZES.seed ? seed : deriveSeed32(seed, PQ_SEED_DOMAIN)

  const { secretKey, publicKey } = ml_dsa65.keygen(seed32)
  const { address, fingerprint } = describePublicKey(publicKey)

  return {
    privateKey: bytesToHex(seed32),
    secretKey: bytesToHex(secretKey),
    publicKey: bytesToHex(publicKey),
    address,
    fingerprint,
  }
}

/** Generate a key pair from fresh random entropy. */
export async function generatePqKeyPair(): Promise<PqKeyPair> {
  return pqKeyPairFromSeed(getRandomBytesSync(PQ_SIZES.seed))
}

/** Derive the PQ key pair for an account from its recovery phrase. */
export async function pqKeyPairFromMnemonic(
  mnemonic: string,
  index = 0,
): Promise<PqKeyPair> {
  return pqKeyPairFromSeed(derivePqSeedFromMnemonic(mnemonic, index))
}

/**
 * Rebuild a key pair from storage.
 *
 * The stored public key is checked against the one the seed regenerates. They
 * can only disagree if the record was corrupted or the two fields came from
 * different wallets — in which case signing would silently produce signatures
 * that do not verify for the displayed address, so fail loudly instead.
 */
export async function pqKeyPairFromStored(
  seedHex: string,
  publicKeyHex: string,
): Promise<PqKeyPair> {
  const pair = await pqKeyPairFromSeed(hexToBytes(seedHex.replace(/^0x/, '')))
  const expected = publicKeyHex.replace(/^0x/, '').toLowerCase()

  if (expected && pair.publicKey.toLowerCase() !== expected) {
    throw new PqKeyError(
      'Stored PQ public key does not match the one derived from the seed — ' +
        'this wallet record is inconsistent and cannot sign for its address.',
    )
  }
  return pair
}

// ─── Signing ────────────────────────────────────────────────────────────────

/**
 * Sign a message with the PQ key identified by `seedHex`.
 *
 * Signing is randomised (the FIPS 204 "hedged" mode noble uses by default),
 * so two signatures over the same message differ. Both verify; this is the
 * recommended mode as it does not rely solely on the secret key for the
 * per-signature nonce.
 *
 * @returns the signature as a hex string.
 */
export async function pqSign(
  message: Uint8Array,
  seedHex: string,
): Promise<string> {
  const { secretKey } = await pqKeyPairFromSeed(hexToBytes(seedHex.replace(/^0x/, '')))
  return bytesToHex(ml_dsa65.sign(message, hexToBytes(secretKey)))
}

/**
 * Sign with the QRDX PQ message prefix.
 *
 * Mirrors EIP-191's purpose: binding a domain prefix to the payload keeps a
 * signature over a user-facing message from being replayable as a signature
 * over a transaction.
 */
export async function pqSignWithPrefix(
  message: string | Uint8Array,
  seedHex: string,
): Promise<string> {
  return pqSign(pqPrefixedMessage(message), seedHex)
}

/**
 * The bytes a prefixed PQ signature covers:
 * `"\x19QRDX PQ Signed Message:\n" + byteLength + message`.
 *
 * The length is the UTF-8 **byte** length, as in the node's
 * `PQWallet.sign_with_prefix`. Using the JS string length (UTF-16 code units)
 * made every non-ASCII message sign different bytes than the node verifies.
 */
export function pqPrefixedMessage(message: string | Uint8Array): Uint8Array {
  const body = typeof message === 'string' ? new TextEncoder().encode(message) : message
  const prefix = new TextEncoder().encode(`\x19QRDX PQ Signed Message:\n${body.length}`)
  const out = new Uint8Array(prefix.length + body.length)
  out.set(prefix, 0)
  out.set(body, prefix.length)
  return out
}

/**
 * Verify a PQ signature against a public key.
 *
 * Returns `false` rather than throwing on malformed input, so callers can treat
 * "bad signature" and "unparseable signature" identically — both mean the
 * signature must not be trusted.
 */
export function pqVerify(
  message: Uint8Array,
  signatureHex: string,
  publicKeyHex: string,
): boolean {
  try {
    return ml_dsa65.verify(
      hexToBytes(signatureHex.replace(/^0x/, '')),
      message,
      hexToBytes(publicKeyHex.replace(/^0x/, '')),
    )
  } catch {
    return false
  }
}

/** Verify a signature produced by {@link pqSignWithPrefix}. */
export function pqVerifyWithPrefix(
  message: string | Uint8Array,
  signatureHex: string,
  publicKeyHex: string,
): boolean {
  return pqVerify(pqPrefixedMessage(message), signatureHex, publicKeyHex)
}

/**
 * Whether real post-quantum signing is available.
 *
 * Now always true: ML-DSA-65 is a pure-JS dependency with no native or WASM
 * prerequisite. Retained so callers written against the previous
 * maybe-available placeholder keep compiling.
 */
export function isPqAvailable(): boolean {
  return true
}

/** Derive the `0xPQ` address for a raw public key. */
export function pqPublicKeyToAddress(publicKeyHex: string): string {
  return describePublicKey(hexToBytes(publicKeyHex.replace(/^0x/, ''))).address
}
