import { describe, it, expect } from 'vitest'
import { execFileSync } from 'node:child_process'
import { validateAddress } from '../../src/core/address'

describe('PQ addresses generated by the node validate in the wallet', () => {
  it('accepts a freshly generated node PQ address', () => {
    const address = execFileSync(
      'ref/qrdx-chain/.venv/bin/python',
      ['-c',
       'import sys; sys.path.insert(0,"ref/qrdx-chain");' +
       'from qrdx.crypto.pq.dilithium import PQPrivateKey; print(PQPrivateKey.generate().address)'],
      { encoding: 'utf8' },
    )
      // liboqs prints a banner to stdout on import; the address is the last line.
      .trim()
      .split('\n')
      .pop()!
      .trim()

    const result = validateAddress(address)
    expect(result.error).toBeNull()
    expect(result.valid).toBe(true)
    expect(result.kind).toBe('pq')
  })
})
