import { describe, it, expect } from 'vitest'
import { validateAddress } from '../../src/core/address'
import { nodePythonHas, runNodePython } from '../node-ref'

// Needs the reference node with liboqs installed (see tests/node-ref.ts).
describe.skipIf(!nodePythonHas('oqs'))('PQ addresses generated by the node validate in the wallet', () => {
  it('accepts a freshly generated node PQ address', () => {
    const address = runNodePython(
      'from qrdx.crypto.pq.dilithium import PQPrivateKey; print(PQPrivateKey.generate().address)',
    )
    const result = validateAddress(address)
    expect(result.error).toBeNull()
    expect(result.valid).toBe(true)
    expect(result.kind).toBe('pq')
  })
})
